import express from "express";
import crypto from "crypto";

import {
  requireAdministrator,
} from "../auth.js";

import {
  socialAuthUrl,
  fetchPublicFeed,
} from "../cms/social.js";

const router = express.Router();

const supportedPlatforms = [
  "linkedin",
  "meta",
  "youtube",
  "x",
];

/*
 * Temporary development storage.
 *
 * Replace this with database-backed storage before
 * production deployment.
 */
const pendingOAuthStates = new Map();
const socialConnections = new Map();

function validatePlatform(
  req,
  res,
  next
) {
  const platform = String(
    req.params.platform || ""
  ).toLowerCase();

  if (
    !supportedPlatforms.includes(platform)
  ) {
    return res.status(400).json({
      message:
        "Unsupported social-media platform.",
      supportedPlatforms,
    });
  }

  req.socialPlatform = platform;

  next();
}

/*
 * Remove OAuth states that are more than
 * ten minutes old.
 */
function removeExpiredStates() {
  const expiryTime =
    Date.now() - 10 * 60 * 1000;

  for (
    const [state, record]
    of pendingOAuthStates.entries()
  ) {
    if (record.createdAt < expiryTime) {
      pendingOAuthStates.delete(state);
    }
  }
}

/*
 * GET /api/admin/social/connections
 */
router.get(
  "/admin/social/connections",
  requireAdministrator,
  (_req, res) => {
    const connections =
      supportedPlatforms.map(
        (platform) => {
          const connection =
            socialConnections.get(
              platform
            );

          return {
            platform,
            connected: Boolean(
              connection?.accessToken
            ),
            authorizationReceived:
              Boolean(
                connection
                  ?.authorizationCodeReceived
              ),
            connectedAt:
              connection?.connectedAt ||
              null,
            accountName:
              connection?.accountName ||
              null,
          };
        }
      );

    res.json({
      connections,
    });
  }
);

/*
 * GET /api/admin/social/:platform/connect
 */
router.get(
  "/admin/social/:platform/connect",
  requireAdministrator,
  validatePlatform,
  (req, res, next) => {
    try {
      removeExpiredStates();

      const platform =
        req.socialPlatform;

      const state =
        crypto
          .randomBytes(32)
          .toString("hex");

      pendingOAuthStates.set(
        state,
        {
          platform,

          /*
           * The current JWT puts the administrator
           * email in req.admin.sub.
           */
          administrator:
            req.admin?.sub || null,

          createdAt: Date.now(),
        }
      );

      const authorizationUrl =
        socialAuthUrl(
          platform,
          state
        );

      res.json({
        platform,
        authorizationUrl,
      });
    } catch (error) {
      next(error);
    }
  }
);

/*
 * GET /api/admin/social/:platform/callback
 *
 * The external social platform redirects to this
 * route, so it cannot use requireAdministrator.
 * Security is provided by validating the OAuth
 * state generated by the protected connect route.
 */
router.get(
  "/admin/social/:platform/callback",
  validatePlatform,
  async (req, res, next) => {
    try {
      removeExpiredStates();

      const platform =
        req.socialPlatform;

      const {
        code,
        state,
        error,
        error_description:
          errorDescription,
      } = req.query;

      if (error) {
        return res
          .status(400)
          .send(`
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="utf-8" />
                <title>Social connection failed</title>
              </head>
              <body>
                <h1>Social connection failed</h1>
                <p>${
                  errorDescription ||
                  error
                }</p>
              </body>
            </html>
          `);
      }

      if (!code || !state) {
        return res
          .status(400)
          .send(`
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="utf-8" />
                <title>Social connection failed</title>
              </head>
              <body>
                <h1>Social connection failed</h1>
                <p>
                  The authorisation response was incomplete.
                </p>
              </body>
            </html>
          `);
      }

      const stateRecord =
        pendingOAuthStates.get(
          String(state)
        );

      if (
        !stateRecord ||
        stateRecord.platform !== platform
      ) {
        return res
          .status(400)
          .send(`
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="utf-8" />
                <title>Social connection failed</title>
              </head>
              <body>
                <h1>Social connection failed</h1>
                <p>
                  The authorisation request was invalid
                  or has expired.
                </p>
              </body>
            </html>
          `);
      }

      pendingOAuthStates.delete(
        String(state)
      );

      /*
       * Do not treat the authorization code as an
       * access token.
       *
       * Platform-specific token exchange must be
       * implemented before the connection can sync
       * or publish content.
       */
      socialConnections.set(
        platform,
        {
          authorizationCodeReceived:
            true,
          connectedAt:
            new Date().toISOString(),
          administrator:
            stateRecord.administrator,
        }
      );

      res.send(`
        <!doctype html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <title>Authorisation received</title>
          </head>

          <body style="
            max-width: 640px;
            margin: 60px auto;
            padding: 24px;
            font-family: Arial, sans-serif;
          ">
            <h1>Authorisation received</h1>

            <p>
              ${platform} returned an authorisation
              code successfully.
            </p>

            <p>
              The platform-specific token exchange
              must now be configured to complete the
              connection.
            </p>

            <button
              type="button"
              onclick="window.close()"
            >
              Close this window
            </button>
          </body>
        </html>
      `);
    } catch (error) {
      next(error);
    }
  }
);

/*
 * POST /api/admin/social/:platform/sync
 */
router.post(
  "/admin/social/:platform/sync",
  requireAdministrator,
  validatePlatform,
  async (req, res, next) => {
    try {
      const platform =
        req.socialPlatform;

      const connection =
        socialConnections.get(
          platform
        );

      if (!connection?.accessToken) {
        return res.status(409).json({
          message:
            `${platform} is not fully connected. ` +
            "Complete the OAuth token exchange first.",
        });
      }

      const items =
        await fetchPublicFeed(
          platform,
          {
            access_token:
              connection.accessToken,

            refresh_token:
              connection.refreshToken,

            account_id:
              connection.accountId,
          }
        );

      res.json({
        platform,
        imported: items.length,
        items,
        syncedAt:
          new Date().toISOString(),
      });
    } catch (error) {
      next(error);
    }
  }
);

/*
 * DELETE /api/admin/social/:platform/connection
 */
router.delete(
  "/admin/social/:platform/connection",
  requireAdministrator,
  validatePlatform,
  (req, res) => {
    const platform =
      req.socialPlatform;

    socialConnections.delete(
      platform
    );

    res.json({
      message:
        `${platform} has been disconnected.`,
    });
  }
);

export default router;